apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
        - name: django
          image: flintsky-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
